# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'einsteinEncodedUI.ui'
#
# Created: Thu Aug  8 16:06:59 2019
#      by: qtpy-uic 2.0.4
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        #Left side of the UI, Plotting, label, and line edit
        self.plotting_widget = QtWidgets.QWidget(self.centralwidget)
        self.plotting_widget.setObjectName("plotting_widget")
        self.verticalLayout.addWidget(self.plotting_widget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        
        #Right side of the UI, two buttons vertically aligned
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.buttonLayout = QtWidgets.QVBoxLayout()
        self.buttonLayout.setSpacing(2)
        self.buttonLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.buttonLayout.setContentsMargins(6, 6, 6, 6)
        self.buttonLayout.setObjectName("buttonLayout")
        
        self.videoToggleButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoToggleButton.sizePolicy().hasHeightForWidth())
        self.videoToggleButton.setSizePolicy(sizePolicy)
        self.videoToggleButton.setObjectName("videoToggleButton")
        self.buttonLayout.addWidget(self.videoToggleButton)
        
        self.shotButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shotButton.sizePolicy().hasHeightForWidth())
        self.shotButton.setSizePolicy(sizePolicy)
        self.shotButton.setMinimumSize(QtCore.QSize(0, 16))
        self.shotButton.setObjectName("shotButton")
        self.buttonLayout.addWidget(self.shotButton)
        
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        
        # Menu options. Need to map all of the functions later
        self.horizontalLayout.addLayout(self.buttonLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 17))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCamera_Seetings = QtWidgets.QMenu(self.menubar)
        self.menuCamera_Seetings.setObjectName("menuCamera_Seetings")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionOpen_Circle_Dictionary = QtWidgets.QAction(MainWindow)
        self.actionOpen_Circle_Dictionary.setObjectName("actionOpen_Circle_Dictionary")
        self.actionVideo_Mode = QtWidgets.QAction(MainWindow)
        self.actionVideo_Mode.setObjectName("actionVideo_Mode")
        self.actionExposure = QtWidgets.QAction(MainWindow)
        self.actionExposure.setObjectName("actionExposure")
        self.actionon = QtWidgets.QAction(MainWindow)
        self.actionon.setObjectName("actionon")
        self.actionoff = QtWidgets.QAction(MainWindow)
        self.actionoff.setObjectName("actionoff")
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addAction(self.actionOpen_Circle_Dictionary)
        self.menuCamera_Seetings.addAction(self.actionVideo_Mode)
        self.menuCamera_Seetings.addAction(self.actionExposure)
        self.menuAbout.addAction(self.actionon)
        self.menuAbout.addAction(self.actionoff)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCamera_Seetings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("", "Welcome To Einstein UI", None, -1))
        self.videoToggleButton.setText(QtWidgets.QApplication.translate("", "Toggle Video", None, -1))
        self.shotButton.setText(QtWidgets.QApplication.translate("", "Take Picture", None, -1))
        self.saveButton.setText(QtWidgets.QApplication.translate("", "Save Image and Data", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("", "File", None, -1))
        self.menuCamera_Seetings.setTitle(QtWidgets.QApplication.translate("", "Camera Settings", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("", "Auto-Settings", None, -1))
        self.actionOpen_Image.setText(QtWidgets.QApplication.translate("", "Open Image", None, -1))
        self.actionOpen_Circle_Dictionary.setText(QtWidgets.QApplication.translate("", "Open Circle Dictionary", None, -1))
        self.actionVideo_Mode.setText(QtWidgets.QApplication.translate("", "Live Steam Mode", None, -1))
        self.actionExposure.setText(QtWidgets.QApplication.translate("", "Single Capture Mode", None, -1))
        self.actionon.setText(QtWidgets.QApplication.translate("", "on", None, -1))
        self.actionoff.setText(QtWidgets.QApplication.translate("", "off", None, -1))

